### ISSUE TITLE
Release a new version?

### ISSUE THREAD

**Issue by briandipalma** [karma-runner/karma-firefox-launcher#102]
The last release was 2 years ago and since then quite a few commits have been merged into the repo, is there any chance of a release?

**Comment by johnjbarton** [comment]
@birtles is this a good time?

**Comment by briandipalma** [comment]
It seems like there is an issue with shutting down Firefox after a test run...we think we can work around it in our tests but I guess that's why you are holding off a release?

**Comment by birtles** [comment]
Yes, I just wanted to verify the Ubuntu issues in #93 and the shutting down issues in #101. I've pinged Moz folks about #101 just now, and I'll dig into the Ubuntu issues today too.

(That said, I'm not even sure I can release a new version. All I know is one day I woke up with write access to the repo somehow.)

**Comment by birtles** [comment]
@johnjbarton I think we're ready to go. I bumped the version and pushed the tags but I don't have permission to publish to npm.

**Comment by johnjbarton** [comment]
done

**Comment by birtles** [comment]
Thank you!
