### ISSUE TITLE
Can you publish a new patch version to fix WSL?

### ISSUE THREAD

**Issue by benjamind** [karma-runner/karma-firefox-launcher#113]
[This commit](https://github.com/karma-runner/karma-firefox-launcher/commit/1eb7e1b145d4e264602eb0b14f7e4777686fb4a7) was added after `1.2.0` was released, and fixes usage under WSL in certain situations.

Could you publish a patch release on NPM to make this fix easier to use?

**Comment by birtles** [comment]
@johnjbarton Would you be able to publish a release?

**Comment by johnjbarton** [comment]
Looks like this project does not have the gruntfile setup common to other karma-runner projects. 

If you commit the update to git I can publish it to npm.  

Or you could set up grunt like the projects and I can run the release script.

**Comment by birtles** [comment]
Ok, I should look into the gruntfile setup sometime. For now I've committed the update.

**Comment by johnjbarton** [comment]
well, I did not realize the `npm run-script release` would bump and then push tags on to my fork.

So now the npm version is 1.3.0 and the tags on github are 1.2.1.  I probably should just have git pull and npm publish, sorry.

**Comment by johnjbarton** [comment]
Should we just try again, at 1.3.1?

**Comment by birtles** [comment]
Let me see if I can work out how to update the tags / changelog on git to match npm.

**Comment by johnjbarton** [comment]
BTW I've had users complain on karma/karma-runner when I dropped nodejs
version in a minor update (they wanted it be major breaking change).

**Comment by birtles** [comment]
> BTW I've had users complain on karma/karma-runner when I dropped nodejs version in a minor update (they wanted it be major breaking change).

Interesting. I dropped support for Node 6 in 9e86d04c243de7203b6a41ba98ea235ae4848337 and that has since been released in 1.2.0 so I guess that ship has sailed.

**Comment by birtles** [comment]
> Let me see if I can work out how to update the tags / changelog on git to match npm.

Ok, I _think_ the version on git including tags, changelog, `package.json` etc. should now match npm.

**Comment by benjamind** [comment]
Thanks!
