### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by birtles** [karma-runner/karma-firefox-launcher#121]
@johnjbarton Would it be possible to release a new version?

In particular it would be good to ship #114 and #116 since they seem to be tripping people up.

Note, however, that it is a breaking change since when we bumped standard-version to 8.0.1 in #117 I had to bump the minimum Node version to version 10.

**Comment by johnjbarton** [comment]
@birtles Let's set this repo to use semantic-release. We've had great luck with it on other karma repos.

This involves a PR to add the modules and connect them to build. It involves adopting a format (which is linted) for commit messages that the release tool understands.  (It may involve some admin I need to do). Then your merges will automatically release.

- Copy [release.config.js](https://github.com/karma-runner/karma-sauce-launcher/blob/a5dc780badb882b77af7d335819491575dcc5844/release.config.js)
- Add `devDependencies` to the `package.json`:
```
"@semantic-release/changelog": "5.0.0",
"@semantic-release/git": "9.0.0",
"@semantic-release/npm": "7.0.4",
"husky": "4.2.3",
```
- Add the husky (linter) config to `package.json`:
```
  "husky": {
    "hooks": {
      "commit-msg": "commitlint -E HUSKY_GIT_PARAMS"
    }
  },
```
- Edit the `travis.yml` to [add the action.](https://github.com/karma-runner/karma-sauce-launcher/blob/d4f7649b2ca418c00ab867e0173e9289a7245c35/.travis.yml) 

If you send the PR for me to review we can get it set up.

**Comment by birtles** [comment]
Great, thank you!

I've started #122 for this.

**Comment by johnjbarton** [comment]
Ok it look worked, thanks!

**Comment by birtles** [comment]
Thank you!
