### ISSUE TITLE
Stopped working since Firefox 90.0.2

### ISSUE THREAD

**Issue by dotnetCarpenter** [karma-runner/karma-firefox-launcher#139]
Thank you for a great launcher!

I was impressed when _karma-firefox-launcher_ just worked in my WSL2 environment. But then I did the mistake of opening Firefox which self updated from verrsion 89 to 90. And now I get `FirefoxHeadless have not captured in 60000 ms, killing`.

Perhaps an argument to Firefox changed?

I'm using _karma-firefox-launcher_ 2.1.1 and the launcher command is `/mnt/c/Program Files/Mozilla Firefox/firefox.exe http://localhost:9876/?id=3697877 -profile \\wsl$\Ubuntu\tmp\karma-3697877 -no-remote -wait-for-browser -headless --start-debugger-server 6000`.

When _karma-firefox-launcher_ tried to open Firefox again, I get an XULRunner dialog error.

![image](https://user-images.githubusercontent.com/43763/127937570-4fad2f67-f607-4d93-b833-017c8b6afe2e.png)
_"Firefox is already running but is not responding" error_

I'm going through the suggestions at https://support.mozilla.org/en-US/kb/firefox-already-running-not-responding and see if that will help.

**Comment by birtles** [comment]
Hmm, it seems to work for me with version 90.

That said, I generally see that error the first time after Firefox self-updates. It normally works for me thereafter. If it persists you might need to check that any existing Firefox processes have been successfully terminated.

**Comment by dotnetCarpenter** [comment]
I had a bunch of Firefox processes running - I killed all of them. Deleted the profile folder and create a fresh one. But nothing seems to work. Which is strange because it was working 2 minutes prior.

If I start Firefox from Karma non-headless, Firefox opens fine but on http://localhost:9876/?id=34929843 it says it can not connect.

Do you want the debug log from cli?

**Comment by birtles** [comment]
> Do you want the debug log from cli?

Sure. Headless works for me but I'm running it from "Git bash".

WSL doesn't work for me for reasons I can't remember (I think it was to do with the default profile path being considered not writeable?).

**Comment by dotnetCarpenter** [comment]
I'm gonna reinstall Firefox and disable Windows Firewall - hopefully that helps.

<details><summary>Here is the log:</summary>
<pre>
> karma start config/karma.conf.js

03 08 2021 02:18:56.331:DEBUG [config]: Loading config /home/dotnet/projects/firefund/firefund-production/config/karma.conf.js
03 08 2021 02:18:56.349:DEBUG [karma-server]: Final config Config {
  LOG_DISABLE: 'OFF',
  LOG_ERROR: 'ERROR',
  LOG_WARN: 'WARN',
  LOG_INFO: 'INFO',
  LOG_DEBUG: 'DEBUG',
  frameworks: [ 'jasmine' ],
  protocol: 'http:',
  port: 9876,
  listenAddress: '0.0.0.0',
  hostname: 'localhost',
  httpsServerConfig: {},
  basePath: '/home/dotnet/projects/firefund/firefund-production',
  files: [
    UrlPattern {
      pattern: 'https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery/jquery.min.js',
      served: false,
      included: true,
      watched: false,
      nocache: false,
      weight: [ 1, 0, 0, 0, 0, 0 ],
      type: undefined,
      isBinary: undefined
    },
    UrlPattern {
      pattern: 'https://cdn.jsdelivr.net/npm/underscore@1.13.1/underscore-min.js',
      served: false,
      included: true,
      watched: false,
      nocache: false,
      weight: [ 1, 0, 0, 0, 0, 0 ],
      type: undefined,
      isBinary: undefined
    },
    Pattern {
      pattern: '/home/dotnet/projects/firefund/firefund-production/public/js/*',
      served: true,
      included: true,
      watched: false,
      nocache: false,
      weight: [ 1, 0, 1, 0, 0, 0 ],
      type: 'js',
      isBinary: undefined
    },
    Pattern {
      pattern: '/home/dotnet/projects/firefund/firefund-production/spec/unit/*.js',
      served: true,
      included: true,
      watched: false,
      nocache: false,
      weight: [ 1, 0, 1, 0, 0, 0 ],
      type: 'js',
      isBinary: undefined
    }
  ],
  browserConsoleLogOptions: { level: 'debug', format: '%b %T: %m', terminal: true },
  customContextFile: null,
  customDebugFile: null,
  customClientContextFile: null,
  exclude: [
    '/home/dotnet/projects/firefund/firefund-production/public/js/client.js',
    '/home/dotnet/projects/firefund/firefund-production/public/js/stripeModal.js',
    '/home/dotnet/projects/firefund/firefund-production/public/js/stripeModalChainedExperiment.js',
    '/home/dotnet/projects/firefund/firefund-production/config/karma.conf.js'
  ],
  logLevel: 'DEBUG',
  colors: true,
  autoWatch: false,
  autoWatchBatchDelay: 250,
  restartOnFileChange: false,
  usePolling: true,
  reporters: [ 'progress' ],
  singleRun: true,
  browsers: [ 'Firefox' ],
  captureTimeout: 60000,
  pingTimeout: 5000,
  proxies: {},
  proxyValidateSSL: true,
  preprocessors: [Object: null prototype] {},
  preprocessor_priority: {},
  urlRoot: '/',
  upstreamProxy: undefined,
  reportSlowerThan: 0,
  loggers: [
    {
      type: 'console',
      layout: { type: 'pattern', pattern: '%[%d{DATE}:%p [%c]: %]%m' }
    }
  ],
  transports: [ 'polling', 'websocket' ],
  forceJSONP: false,
  plugins: [ 'karma-*' ],
  client: {
    args: [],
    useIframe: true,
    runInParent: false,
    captureConsole: true,
    clearContext: true
  },
  defaultClient: {
    args: [],
    useIframe: true,
    runInParent: false,
    captureConsole: true,
    clearContext: true
  },
  browserDisconnectTimeout: 2000,
  browserDisconnectTolerance: 0,
  browserNoActivityTimeout: 30000,
  processKillTimeout: 2000,
  concurrency: 1,
  failOnEmptyTestSuite: true,
  retryLimit: 2,
  detached: false,
  crossOriginAttribute: true,
  browserSocketTimeout: 20000,
  cmd: 'start',
  configFile: '/home/dotnet/projects/firefund/firefund-production/config/karma.conf.js'
}
03 08 2021 02:18:56.350:DEBUG [plugin]: Loading karma-* from /home/dotnet/projects/firefund/firefund-production/node_modules
03 08 2021 02:18:56.421:DEBUG [plugin]: Loading plugin /home/dotnet/projects/firefund/firefund-production/node_modules/karma-firefox-launcher.
03 08 2021 02:18:58.123:DEBUG [plugin]: Loading plugin /home/dotnet/projects/firefund/firefund-production/node_modules/karma-jasmine.
03 08 2021 02:18:58.140:DEBUG [web-server]: Instantiating middleware
03 08 2021 02:18:58.206:DEBUG [filelist]: Excluded file "/home/dotnet/projects/firefund/firefund-production/public/js/client.js"
03 08 2021 02:18:58.208:DEBUG [filelist]: Excluded file "/home/dotnet/projects/firefund/firefund-production/public/js/stripeModal.js"
03 08 2021 02:18:58.209:DEBUG [filelist]: Excluded file "/home/dotnet/projects/firefund/firefund-production/public/js/stripeModalChainedExperiment.js"
03 08 2021 02:18:58.249:INFO [karma-server]: Karma v6.3.4 server started at http://localhost:9876/
03 08 2021 02:18:58.252:INFO [launcher]: Launching browsers Firefox with concurrency 1
03 08 2021 02:18:58.266:INFO [launcher]: Starting browser Firefox
03 08 2021 02:18:58.269:DEBUG [launcher]: null -> BEING_CAPTURED
03 08 2021 02:18:58.271:DEBUG [temp-dir]: Creating temp dir at /tmp/karma-34929843
03 08 2021 02:18:58.331:DEBUG [launcher]: /mnt/c/Program Files/Mozilla Firefox/firefox.exe http://localhost:9876/?id=34929843 -profile \\wsl$\Ubuntu\tmp\karma-34929843 -no-remote -wait-for-browser
03 08 2021 02:19:58.315:WARN [launcher]: Firefox have not captured in 60000 ms, killing.
03 08 2021 02:19:58.316:DEBUG [launcher]: BEING_CAPTURED -> BEING_KILLED
03 08 2021 02:19:58.319:DEBUG [launcher]: Process Firefox exited with code null and signal SIGTERM
03 08 2021 02:19:58.319:DEBUG [temp-dir]: Cleaning temp dir /tmp/karma-34929843
03 08 2021 02:19:58.362:INFO [launcher]: Trying to start Firefox again (1/2).
03 08 2021 02:19:58.362:DEBUG [launcher]: BEING_KILLED -> RESTARTING
03 08 2021 02:19:58.363:DEBUG [launcher]: RESTARTING -> FINISHED
03 08 2021 02:19:58.363:DEBUG [launcher]: FINISHED -> FINISHED
03 08 2021 02:19:58.363:DEBUG [launcher]: Restarting Firefox
03 08 2021 02:19:58.364:DEBUG [launcher]: FINISHED -> BEING_CAPTURED
03 08 2021 02:19:58.364:DEBUG [temp-dir]: Creating temp dir at /tmp/karma-34929843
03 08 2021 02:19:58.371:DEBUG [launcher]: /mnt/c/Program Files/Mozilla Firefox/firefox.exe http://localhost:9876/?id=34929843 -profile \\wsl$\Ubuntu\tmp\karma-34929843 -no-remote -wait-for-browser
03 08 2021 02:20:58.419:WARN [launcher]: Firefox have not captured in 60000 ms, killing.
03 08 2021 02:20:58.420:DEBUG [launcher]: BEING_CAPTURED -> BEING_KILLED
03 08 2021 02:20:58.421:DEBUG [launcher]: Process Firefox exited with code null and signal SIGTERM
03 08 2021 02:20:58.421:DEBUG [temp-dir]: Cleaning temp dir /tmp/karma-34929843
03 08 2021 02:20:58.426:INFO [launcher]: Trying to start Firefox again (2/2).
03 08 2021 02:20:58.426:DEBUG [launcher]: BEING_KILLED -> RESTARTING
03 08 2021 02:20:58.427:DEBUG [launcher]: RESTARTING -> FINISHED
03 08 2021 02:20:58.427:DEBUG [launcher]: FINISHED -> FINISHED
03 08 2021 02:20:58.427:DEBUG [launcher]: Restarting Firefox
03 08 2021 02:20:58.427:DEBUG [launcher]: FINISHED -> BEING_CAPTURED
03 08 2021 02:20:58.427:DEBUG [temp-dir]: Creating temp dir at /tmp/karma-34929843
03 08 2021 02:20:58.435:DEBUG [launcher]: /mnt/c/Program Files/Mozilla Firefox/firefox.exe http://localhost:9876/?id=34929843 -profile \\wsl$\Ubuntu\tmp\karma-34929843 -no-remote -wait-for-browser
03 08 2021 02:21:58.481:WARN [launcher]: Firefox have not captured in 60000 ms, killing.
03 08 2021 02:21:58.482:DEBUG [launcher]: BEING_CAPTURED -> BEING_KILLED
03 08 2021 02:21:58.483:DEBUG [launcher]: Process Firefox exited with code null and signal SIGTERM
03 08 2021 02:21:58.483:DEBUG [temp-dir]: Cleaning temp dir /tmp/karma-34929843
03 08 2021 02:21:58.485:ERROR [launcher]: Firefox failed 2 times (timeout). Giving up.
03 08 2021 02:21:58.486:DEBUG [karma-server]: Run complete, exiting.
03 08 2021 02:21:58.487:DEBUG [launcher]: Disconnecting all browsers
03 08 2021 02:21:58.488:DEBUG [launcher]: BEING_KILLED -> BEING_FORCE_KILLED
03 08 2021 02:21:58.488:DEBUG [proxy]: Destroying proxy agents
03 08 2021 02:21:58.488:DEBUG [launcher]: BEING_FORCE_KILLED -> FINISHED
03 08 2021 02:21:58.488:DEBUG [launcher]: FINISHED -> FINISHED
</pre>
</details>

**Comment by dotnetCarpenter** [comment]
Hmm.. There seems to be something wrong with my WSL.
I just got this after a reboot:

```
[error 0x8007010b when launching `wsl.exe -d Ubuntu']
Could not access starting directory "//wsl$/Ubuntu/home/dotnet/"
```

After booting into WSL in an elevated PowerShell, my usual terminal began to work again and so did `karma start config/karma.conf.js` with karma-firefox-launcher!

Thanks for your quick reply @birtles

**Comment by birtles** [comment]
No problem! Glad to hear it works!

I also often come across WSL being unstable and have to restart (`wsl --shutdown`).

**Comment by dotnetCarpenter** [comment]
I use `Stop-Service LxssManager` and `Start-Service LxssManager` from an Admin PowerShell which I guess do the same. But thanks for the tip 😄
