### ISSUE TITLE
ability to change Firefox location

### ISSUE THREAD

**Issue by juanpablo-santos** [karma-runner/karma-firefox-launcher#20]
it would be nice to have the ability to select a custom location for firefox. 

For example, it could be done by replacing line 31 on `index.js`, with something like:

``` javascript
if( process.env.KARMABROWSERLOC !== null ) {
  return process.env.KARMABROWSERLOC + \\firefox.exe
}

return 'C:\\Program Files' + suffix /* or maybe even better return firefox.exe and assume it's present on PATH */
```

this would allow to use a portable Firefox, or to use a Firefox instance installed elsewhere (f.ex., due to admin restrictions on some folders)

**Comment by adjenks** [comment]
It doesn't mention the _ENV variables anywhere in the docs.;

**Comment by birtles** [comment]
> It doesn't mention the _ENV variables anywhere in the docs.

I just added some docs now.
