### ISSUE TITLE
Immediate disconnection on io.js 1.0.3

### ISSUE THREAD

**Issue by mzgol** [karma-runner/karma-firefox-launcher#27]
Steps to reproduce:
1. `git clone https://github.com/mzgol/grunt-ng-annotate.git`
2. `cd karma-ng-json2js-preprocessor`
2. `npm install karma-firefox-launcher@0.1.4` (currently the latest version).
2. Add `'Firefox'` to the array in line 92 (https://github.com/EE/karma-ng-json2js-preprocessor/blob/b10cd52939e814ab499fc97c507c3738221ca167/karma.conf.js#L92)
3. Run `npm test`.

Effect: Chrome passes, Firefox immediately disconnects, hanging the whole process; screenshot:
![screen shot 2015-01-21 at 06 14 24](https://cloud.githubusercontent.com/assets/1758366/5831527/cb7365ea-a134-11e4-94a0-ec492b1e9fac.png)

It works fine on Node 0.10.35 & 0.11.15. All attempts were made using the same npm version, `2.3.0` (that shouldn't matter, though).

**Comment by mzgol** [comment]
iojs/io.js#456

**Comment by mzgol** [comment]
Something must have changed on the io.js side. It doesn't work in 1.0.4 but it works fine in 1.1.0.

I'm closing this issue then!

**Comment by kentcdodds** [comment]
I've been back and forth battling with this for a long time (evidently as long as I've had io.js installed) and I finally found this issue which prompted me to finally upgrade from 1.0.2 to 1.5.1 and everything's working now. Thanks @mzgol! :-)
