### ISSUE TITLE
Error "Your Firefox profile cannot be loaded. It may be missing or inaccessible."

### ISSUE THREAD

**Issue by Krinkle** [karma-runner/karma-firefox-launcher#28]
Running under Xvfb on Ubuntu 14.04 (Trusty).

This doesn't happen often, but it sometimes does:

```
INFO [karma]: Karma v0.12.31 server started at http://localhost:9876/
INFO [launcher]: Starting browser Chrome
INFO [launcher]: Starting browser Firefox
INFO [Chromium 41.0.2272 (Ubuntu)]: Connected on socket zQbHgwVpW95eCoI6HxQX with id 25180188
......................................
Chromium 41.0.2272 (Ubuntu): Executed 38 of 38 SUCCESS (0.245 secs / 0.231 secs)

WARN [launcher]: Firefox have not captured in 90000 ms, killing.
INFO [launcher]: Trying to start Firefox again (1/2).
WARN [launcher]: Firefox have not captured in 90000 ms, killing.
INFO [launcher]: Trying to start Firefox again (2/2).
WARN [launcher]: Firefox have not captured in 90000 ms, killing.
ERROR [launcher]: Firefox failed 2 times (timeout). Giving up.
```

```
jenkins+ 10879  0.3  0.4 842804 38356 pts/1    Sl+  23:57   0:00 npm test                      
jenkins+ 10885  0.0  0.0   4444   660 pts/1    S+   23:57   0:00 sh -c grunt test
jenkins+ 10886  3.1  1.5 1040152 129264 pts/1  Sl+  23:57   0:04 grunt                   
jenkins+ 11886  0.4  0.6 390864 51300 pts/1    Sl+  23:58   0:00 /usr/lib/firefox/firefox http://localhost:9876/?id=26795693 -profile /tmp/karma-26795693 -no-remote
```

It seems to be blocked on this popup: (Captured from Xvfb using ImageMagic's `import`.)
![image](https://cloud.githubusercontent.com/assets/156867/6587885/743782d0-c78a-11e4-9710-9783b4e4e01f.png)

**Comment by Krinkle** [comment]
Looks like this was caused by a permissions problem. I was simulating the tests from my user account over ssh using `sudo -su jenkins-slave` instead of `sudo -iu jenkins-slave`. As such, it inherited my environment variables and preserved `HOME` (which the other user is not allowed to write to).

Presumably something in karma-firefox-launcher or firefox writes to the user's home directory and doesn't give any error if it failed to create the profile.

**Comment by hashar** [comment]
Two+ years later and I have hit the same issue. This time running Firefox in a Docker container as user `nobody`. In such a case `$HOME` is set to the non existent directory `/nonexistent`.

Notably Firefox creates
```
$ tree -aCF /nonexistent/
/nonexistent/
├── Desktop/
└── .mozilla/
    ├── extensions/
    └── firefox/
        └── Crash Reports/
            ├── events/
            └── InstallTime20171114221957
```

**Comment by janopae** [comment]
> One way to workaround it: HOME=/tmp/firefox firefox :D

This workaround sadly does not work any more, as Karma now creates dynamic temp directories based on the PID, and deletes them after the process stopped.

I can at least locally work around this by declaring a custom runner, that uses my personal Firefox profile from the Firefox Snap in my home directory (ugh!) like this:

```js
// karma.cong.json
// ...
    browsers: ['FirefoxFixed'],
    customLaunchers: {
      FirefoxFixed: {
        base: 'Firefox',
        name: 'FirefoxFixed',
        profile: '/home/jano/snap/firefox/common/.mozilla/firefox/cscfzy0o.default'
      }
    },
// ...
```

But this is not something I would commit to my repo :D (and it won't work in CI of course)

When and how is the profile directory supposed to be created? Any chance I could debug this somehow?

**Comment by pubkey** [comment]
I had the same problem for years on ubuntu.
The solution was to remove the snap installed firefox and reinstall it with apt-get:
https://www.omgubuntu.co.uk/2022/04/how-to-install-firefox-deb-apt-ubuntu-22-04

**Comment by dave-kennedy** [comment]
As an alternative you could store the test profile in the project root directory:

```
    customLaunchers: {
      FirefoxTest: {
        base: 'Firefox',
        profile: require('path').join(__dirname, './.karma')
      }
    },
```

Requires creating the directory first.
