### ISSUE TITLE
No README data

### ISSUE THREAD

**Issue by kentcdodds** [karma-runner/karma-firefox-launcher#29]
When I npm install this package I get the error:

```
npm WARN package.json karma-firefox-launcher@0.1.4 No README data
```

Normally I only see that when a package doesn't have a README.md file, but this one has one, so I'm not sure what the problem is. You'll notice that it doesn't have any README.md data on the package listing on [npmjs.org](https://www.npmjs.com/package/karma-firefox-launcher). But I'd really like to get rid of this warning as it clutters up my warnings and makes it difficult for me to find real issues.

**Comment by inolasco** [comment]
+1

**Comment by kentcdodds** [comment]
I no longer use this project, so I'll go ahead and close this.
