### ISSUE TITLE
Can not find the binary /Applications/FirefoxDeveloper.app/Contents/MacOS/firefox-bin

### ISSUE THREAD

**Issue by tkrotoff** [karma-runner/karma-firefox-launcher#31]
On my Mac (OS X 10.10), Firefox Developer Edition is installed inside `/Applications/FirefoxDeveloperEdition.app/`

**Comment by tkrotoff** [comment]
There is already a PR for this issue: #24

**Comment by zzo** [comment]
merged and push to npm @ .1.5
