### ISSUE TITLE
Allow developers to set custom user preferences

### ISSUE THREAD

**Issue by letchoo** [karma-runner/karma-firefox-launcher#39]
In the karma config file, for the firefox launcher, I would like to be able to add on my own user preferences when I am creating a custom launcher in the config.

Example of how it looks:
```
customerLaunchers: {
  FirefoxCustomerLauncher: {
    base: 'Firefox',
    prefs: {
       "media.navigator.permission.disabled": true, 
       "media.getusermedia.screensharing.enabled": true
    }
  },
}
```

This gives more expandability in testing especially in cases where you require to configure the user preferences.

Thanks.

**Comment by tienthanh8490** [comment]
+1

**Comment by johache** [comment]
According to the doc and to my tests this issue is fixed.

**Comment by Dignifiedquire** [comment]
Thanks @johache you are right.
