### ISSUE TITLE
Pull Request Testing Fails

### ISSUE THREAD

**Issue by barakhaim** [karma-runner/karma-firefox-launcher#48]
Hi,

I've created a pull request and it had failed the CI testing. Out of curiosity it tried running the tests on the original code and surprise surprise - it breaks the build as well.

It seems to be an internal problem with the CI configs (error appended at the end).
Please look into it.

Thank you!

--Barak

Worker information
hostname: travis-worker-gce-org-prod-4:846ab6e9-397e-4ce8-bc02-0d98ebfc9d50
version: v2.0.0-24-g8f5b41a https://github.com/travis-ci/worker/tree/8f5b41a07b602643e7ee8cf307787f9ca8f4b00b
instance: testing-gce-3393c64d-ffe0-4fd5-9672-c3a69b7606e5:travis-ci-ruby-precise-1450195856
startup: 23.708292799s
Could not find .travis.yml, using standard configuration.
system_info
Build system information
Build language: ruby
Build group: stable
Build dist: precise
Build image provisioning date and time
Tue Dec 15 16:36:18 UTC 2015
Operating System Details
Distributor ID: Ubuntu
Description:    Ubuntu 12.04.5 LTS
Release:    12.04
Codename:   precise
Linux Version
3.13.0-63-generic
Cookbooks Version
fad6c97 https://github.com/travis-ci/travis-cookbooks/tree/fad6c97
Git version
git version 1.8.5.6
bash version
GNU bash, version 4.2.25(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2011 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later http://gnu.org/licenses/gpl.html
This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
GCC version
gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3
Copyright (C) 2011 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
LLVM version
clang version 3.4 (tags/RELEASE_34/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
Pre-installed Ruby versions
ree-1.8.7-2012.02
ruby-1.8.7-p374
ruby-1.9.2-p330
ruby-1.9.3-p551
ruby-2.0.0-p647-clang
ruby-2.1.2
ruby-2.1.3
ruby-2.1.4
ruby-2.1.5
ruby-2.2.0
Pre-installed Node.js versions
v0.10.36
Pre-installed Go versions
1.4.2
mysql --version
mysql  Ver 14.14 Distrib 5.5.46, for debian-linux-gnu (x86_64) using readline 6.2
Pre-installed PostgreSQL versions
9.1.19
9.2.14
9.3.10
9.4.5
Redis version
redis-server 3.0.5
riak version
2.1.3
MongoDB version
MongoDB 2.4.14
CouchDB version
couchdb 1.6.1
Neo4j version
1.9.4
Cassandra version
2.0.9
ElasticSearch version
1.4.0
Installed Sphinx versions
2.0.10
2.1.9
2.2.6
Default Sphinx version
2.2.6
Installed Firefox version
firefox 38.4.0esr
PhantomJS version
1.9.8
ant -version
Apache Ant(TM) version 1.8.2 compiled on December 3 2011
mvn -version
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T17:29:23+00:00)
Maven home: /usr/local/maven
Java version: 1.7.0_80, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-7-oracle/jre
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-63-generic", arch: "amd64", family: "unix"
git.checkout
NaNs$ git clone --depth=50 https://github.com/karma-runner/karma-firefox-launcher.git karma-runner/karma-firefox-launcher
Cloning into 'karma-runner/karma-firefox-launcher'...
remote: Counting objects: 192, done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 192 (delta 0), reused 9 (delta 0), pack-reused 183
Receiving objects: 100% (192/192), 31.35 KiB | 0 bytes/s, done.
Resolving deltas: 100% (96/96), done.
Checking connectivity... done.
$ cd karma-runner/karma-firefox-launcher
0.54s$ git fetch origin +refs/pull/47/merge:
remote: Counting objects: 7, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 7 (delta 2), reused 2 (delta 2), pack-reused 1
Unpacking objects: 100% (7/7), done.
From https://github.com/karma-runner/karma-firefox-launcher
- branch            refs/pull/47/merge -> FETCH_HEAD
  $ git checkout -qf FETCH_HEAD
  0.00s
  rvm
  0.11s$ rvm use default
  Using /home/travis/.rvm/gems/ruby-1.9.3-p551
  $ ruby --version
  ruby 1.9.3p551 (2014-11-13 revision 48407) [x86_64-linux]
  $ rvm --version
  rvm 1.26.10 (1.26.10) by Wayne E. Seguin wayneeseguin@gmail.com, Michal Papis mpapis@gmail.com [https://rvm.io/]
  $ bundle --version
  Bundler version 1.7.6
  $ gem --version
  2.5.1
  0.11s$ rake
  rake aborted!
  No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)
  /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `eval'
  /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in`<main>'
  (See full trace by running task with --trace)
  The command "rake" exited with 1.
  Done. Your build exited with 1.

**Comment by Dignifiedquire** [comment]
There is no proper travis configuration yet, so at the moment you can ignore it.

**Comment by barakhaim** [comment]
Great! 
So will you look at my pull request?

**Comment by birtles** [comment]
This should be working now.
