### ISSUE TITLE
Error during loading "karma-firefox-launcher" plugin:   Cannot read property 'substr' of undefined

### ISSUE THREAD

**Issue by m777** [karma-runner/karma-firefox-launcher#67]
We face the following error in our CI infrastructure on Windows Servers with your new 1.0.1 release:

```
ERROR [plugin]: Error during loading "karma-firefox-launcher" plugin:
  Cannot read property 'substr' of undefined
```

This happens as you access the "PATH" variable in a way, not every bash support:
`var paden = process.env.Path.split(';') `

Please use "PATH" or ["PATH"], to be able to run also on Windows machines using gitbash or cygwin.

**Comment by lexmuc** [comment]
I'm having the same problem when trying to start karma just with the standard windows shell. Is there a kind of workaround until it is fixed?

**Comment by jtarkowski** [comment]
Just had the same problem on Windows 32bit. How can I fix it?

**Comment by droooney** [comment]
The same. Windows 7 32bit.

**Comment by iH8** [comment]
The fix referenced by LeonardoVal works, please merge...
