### ISSUE TITLE
Use firefox headless mode

### ISSUE THREAD

**Issue by LoveIsGrief** [karma-runner/karma-firefox-launcher#76]
Hi,

Since [FF55 it's possible to use the `-headless` flag](https://developer.mozilla.org/en-US/Firefox/Headless_mode). I would be nice to have it added to the options passed to firefox or add a `FirefoxHeadlessBrowser`.

Cheers

**Comment by keithamus** [comment]
In the meantime it is quite simple to set this up. Here is the minimum config options you need:

```js
module.exports = config => {
  config.set({
    browsers: ['FirefoxHeadless'],
    customLaunchers: {
      FirefoxHeadless: {
        base: 'Firefox',
        flags: [ '-headless' ],
      },
    },
  })
}
```

**Comment by applecool** [comment]
Does Firefox has more flags like `ignoreSSL`?

**Comment by luissmg** [comment]
@jscharett can you provide your `customLaunchers`? and do you have `karma-firefox-launcher` installed?

**Comment by jscharett** [comment]
I have `karma-firefox-launcher: 1.1.0` installed.  I used the customLaunchers noted by @keithamus

**Comment by birtles** [comment]
> Maybe the README could be updated to reflect those options?

Added a mention in cfb2e38b93b6cf9e7f9f41d40fec21fc3ed93073.

**Comment by AshuSingh07** [comment]
install karma-firefox-launcher via npm:
npm install karma-firefox-launcher --save-dev
